### ISSUE TITLE
anchorEarn.balance error

### ISSUE THREAD

**Issue by SmartAppsX** [Anchor-Protocol/anchor-earn#10]
I got this error after query the balance with anchorEarn.balance

 Cannot read property 'amount' of undefined
    at TerraAnchorEarn.<anonymous> (\node_modules\@anchor-protocol\anchor-earn\dist\facade\terra-anchor-earn.js:325:71)
    at Generator.next (<anonymous>)
    at fulfilled (\node_modules\@anchor-protocol\anchor-earn\dist\facade\terra-anchor-earn.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by SmartAppsX** [comment]
It seems to happen when the account is recently created and doesn't have any funds.

terra-anchor-earn.js 

account_balance: getNaturalDecimals(accountBalance[0].amount.toString()),

In this line the var accountBalance is undefined and can't access to the [0] item

**Comment by MSNTCS** [comment]
Thanks for the report, we will reflect that on the new release.

**Comment by kiruthikraaj** [comment]
Is this issue resolved ? I am still facing the error.

**Comment by diegodelrieu** [comment]
Having the same issue, seemingly not resolved yet.

**Comment by MSNTCS** [comment]
@SmartAppsX thank you for the report. @diegodelrieu @kiruthikraaj v1.1.1 is just released, please use that. That has the fix.

**Comment by kiruthikraaj** [comment]
Great Thanks for the update.
